# Generated by Django 5.1.4 on 2024-12-19 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maquina',
            old_name='tipo',
            new_name='marca',
        ),
        migrations.RenameField(
            model_name='reparacion',
            old_name='observaciones',
            new_name='solucion',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='maquina',
            name='fecha_entrada',
        ),
        migrations.RemoveField(
            model_name='maquina',
            name='id_unico',
        ),
        migrations.RemoveField(
            model_name='maquina',
            name='problema',
        ),
        migrations.RemoveField(
            model_name='reparacion',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='reparacion',
            name='mano_obra',
        ),
        migrations.RemoveField(
            model_name='reparacion',
            name='total',
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='modelo',
            field=models.CharField(default='Desconcido', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reparacion',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reparacion',
            name='fecha_ingreso',
            field=models.DateField(auto_now_add=True, default='2024-12-19'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reparacion',
            name='problema_reportado',
            field=models.TextField(default='Sin descripcion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maquinas', to='maquinas.cliente'),
        ),
        migrations.DeleteModel(
            name='DetalleReparacion',
        ),
    ]
