# Generated by Django 5.1.4 on 2024-12-21 22:40

import datetime
import django.db.models.deletion
import maquinas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0002_rename_tipo_maquina_marca_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maquina',
            old_name='marca',
            new_name='tipo',
        ),
        migrations.RenameField(
            model_name='reparacion',
            old_name='solucion',
            new_name='observaciones',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='maquina',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='maquina',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='reparacion',
            name='costo',
        ),
        migrations.RemoveField(
            model_name='reparacion',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='reparacion',
            name='problema_reportado',
        ),
        migrations.AddField(
            model_name='maquina',
            name='fecha_entrada',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='maquina',
            name='id_unico',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='maquina',
            name='problema',
            field=models.TextField(default='Desconocido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reparacion',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='reparacion',
            name='mano_obra',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reparacion',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='cliente',
            field=models.ForeignKey(default=maquinas.models.cliente_generico, on_delete=django.db.models.deletion.CASCADE, related_name='maquinas', to='maquinas.cliente'),
        ),
        migrations.CreateModel(
            name='DetalleReparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('descripcion', models.CharField(max_length=255)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reparacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='maquinas.reparacion')),
            ],
        ),
    ]
