# Generated by Django 5.1.4 on 2024-12-22 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0003_rename_marca_maquina_tipo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallereparacion',
            old_name='total',
            new_name='precio',
        ),
    ]
