# Generated by Django 5.1.4 on 2024-12-22 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0004_rename_total_detallereparacion_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reparacion',
            name='total',
        ),
        migrations.AddField(
            model_name='reparacion',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='maquinas.cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detallereparacion',
            name='precio',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reparacion',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reparacion',
            name='mano_obra',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reparacion',
            name='maquina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maquinas.maquina'),
        ),
        migrations.AlterField(
            model_name='reparacion',
            name='observaciones',
            field=models.TextField(default='Sin Observaciones'),
            preserve_default=False,
        ),
    ]
