# Generated by Django 5.1.4 on 2024-12-22 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0006_rename_tipo_maquina_maquina_alter_maquina_problema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='problema',
            field=models.TextField(),
        ),
    ]
