# Generated by Django 5.1.4 on 2024-12-29 00:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0008_reparacion_id_unico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparacion',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
