# Generated by Django 5.1.4 on 2025-01-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0009_alter_reparacion_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('reparada', 'Reparada')], default='pendiente', max_length=10),
        ),
    ]
